import { 
  authApi, 
  blogApi, 
  productApi, 
  brandApi, 
  categoryApi, 
  subcategoryApi, 
  serviceApi, 
  quoteApi, 
  flavorApi, 
  healthApi 
} from './restApi';

// Import GraphQL hooks
import {
  useCreateBrand,
  useUpdateBrand,
  useDeleteBrand,
  useBrands,
  useBrand,
  useCreateProduct,
  useUpdateProduct,
  useDeleteProduct,
  useProducts,
  useProduct,
  useCreateCategory,
  useUpdateCategory,
  useDeleteCategory,
  useCategories,
  useCategory,
  useCreateBlog,
  useUpdateBlog,
  useDeleteBlog,
  useBlogs,
  useBlog,
  useCreateService,
  useUpdateService,
  useDeleteService,
  useServices,
  useService,
  useCreateFlavor,
  useUpdateFlavor,
  useDeleteFlavor,
  useFlavors,
  useFlavor,
  useLogin,
  useRegister,
  useCreateUser,
  useUpdateUser,
  useDeleteUser
} from '../hooks';

// Export all API functions
export {
  authApi,
  blogApi,
  productApi,
  brandApi,
  categoryApi,
  subcategoryApi,
  serviceApi,
  quoteApi,
  flavorApi,
  healthApi
};

// Export GraphQL hooks
export {
  useCreateBrand,
  useUpdateBrand,
  useDeleteBrand,
  useBrands,
  useBrand,
  useCreateProduct,
  useUpdateProduct,
  useDeleteProduct,
  useProducts,
  useProduct,
  useCreateCategory,
  useUpdateCategory,
  useDeleteCategory,
  useCategories,
  useCategory,
  useCreateBlog,
  useUpdateBlog,
  useDeleteBlog,
  useBlogs,
  useBlog,
  useCreateService,
  useUpdateService,
  useDeleteService,
  useServices,
  useService,
  useCreateFlavor,
  useUpdateFlavor,
  useDeleteFlavor,
  useFlavors,
  useFlavor,
  useLogin,
  useRegister,
  useCreateUser,
  useUpdateUser,
  useDeleteUser
};

// Re-export types
export type {
  Blog,
  CreateBlogInput,
  UpdateBlogInput,
  LoginInput,
  RegisterInput,
  AuthResponse,
  Product,
  CreateProductInput,
  UpdateProductInput,
  Brand,
  CreateBrandInput,
  UpdateBrandInput,
  Category,
  CreateCategoryInput,
  UpdateCategoryInput,
  SubCategory,
  Service,
  CreateServiceInput,
  UpdateServiceInput,
  Quote,
  UpdateQuoteInput,
  Flavor,
  CreateFlavorInput,
  UpdateFlavorInput,
  FlavorSize,
  FlavorNutritionalInfo,
  FlavorSeasonality
} from './restApi';

// Default export for convenience
export default {
  auth: authApi,
  blogs: blogApi,
  products: productApi,
  brands: brandApi,
  categories: categoryApi,
  subcategories: subcategoryApi,
  services: serviceApi,
  quotes: quoteApi,
  flavors: flavorApi,
  health: healthApi
}; 